#from .asserttool import asserttool
#from .asserttool import am_root
from .asserttool import maxone
from .asserttool import minone
from .asserttool import nevd
from .asserttool import nl_iff_tty
from .asserttool import one
from .asserttool import pause
from .asserttool import root_user
from .asserttool import verify
